### ISSUE TITLE
Create new hangman image.

### ISSUE THREAD

**Issue by WilmingtonDavid** [WilmingtonDavid/HangManProject#9]

**Comment by courtneyj3573** [comment]
- Starting 
First mistake - Lose buttons
Second mistake - Lose arm
Third mistake - Lose other arm
Fourth mistake - Lose bottom
Fifth mistake - Lose middle 
Sixth mistake - Lose nose
Seventh mistake- Loss/Lose game image
New game
Start game menu ?

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154129-a9fa79ed-fee8-489b-9a8f-7f9844fd8aa5.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154159-511937c3-e707-47c4-8c39-a96c629ee427.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154181-2fa7a511-1948-41e1-af35-26f4c6716421.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154200-6d89aba6-dc37-48a8-a01d-04146e267299.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154219-26ddaf3b-299a-41de-8a7f-0babb4366ffa.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154238-6e980805-9895-4cb4-af7d-495e3b8360c1.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154249-c9eeeb41-0d56-4f30-9ae2-994fee000a90.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154264-c1f932e9-fbd8-4e64-9505-db05228c7d50.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141154275-67311a13-b654-4836-9d76-3c077294c30b.png)

**Comment by courtneyj3573** [comment]
![image](https://user-images.githubusercontent.com/86331506/141520938-9bfafdec-278d-47c0-a7ef-7a4e8b9920b2.png)
